services:
  blockpi_proxy:
    container_name: blockpi_proxyapi
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID:-1000}
        - GROUP_ID=${GROUP_ID:-1000}
    volumes:
      - ./:/home/komodian/api
    ports:
      - 127.0.0.1:${FASTAPI_PORT:-8528}:${FASTAPI_PORT:-8528}
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    restart: always
    command: ["poetry", "run", "python3.12", "main.py"]
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
